### ISSUE TITLE
Comments on the implementation

### ISSUE THREAD

**Issue by sbillard** [f1dot4/zenLdap#1]
You have attached two empty filters:

zp_register_filter('','ldapLogon::checkLogon');
zp_register_filter('','ldapLogon::getLogon');

Classes should have already been loaded before your library is loaded.

If you did want these active, you would need to supply the approriate filter hook name:

Your alternate to lib-auth really should be extending the Zenphoto_Authorty and Zenphoto_Admininistrator classes. Replacing them as you have done will make it almost impossible to keep up with changes made in the mainline Zenphoto releases. It also makes it difficult to critique your changes as they are not obvious. 

If you did simply override/extend the Zenphoto_Authority class methods for checkAuthorization and handleLogon then there would be no need for an option for ldapEnabled. presumably if this feature is installed it should be enabled.

There is also no need for a plugin if you are taking the lib-auth extension route. Just include your ldapLogon class with your Zenphoto_Authority extension. Add  your options to by extending the ldapLogon method.

Also, as I see no Zenphoto_Administrator class, I do not see how this can work at all.

The proscribed way of using an alternate Lib-auth is to have your code "require" the original, extend the classes as needed and instantiat your version of the Zenphoto_Administrator class as $_zp_authority.

BUT: I really do not understand why you did not take the approach of implementing an external authority plugin like the MyBB one I sent you. It does appear that the LDAP authentication gives you sufficient information to create a transient Zenphoto user the way that method does.

**Comment by gevatter** [comment]
@sbillard 
i don't know whats the best way to contat you, because you dont provided a contact address so i try it this way. 
I want to write an ldap plugin. This one doesn't seem to work any longer and as far as i understand it has some problems in its implementation. 
I can't find any documentation how to work with the external_auth class so before fiddling around I want to ask you, if you can give me a hint or some example as you said you did bevore in this old thred I found: http://www.zenphoto.org/support/topic.php?id=8702 .
If this is not possible is there any documentation how to implement such a plugin the best way?

**Comment by sbillard** [comment]
I currently work on the ZenPhoto20 branch of this software. We can use its Issues for communications.https://github.com/ZenPhoto20/ZenPhoto20/issues

I will be glad to work with you on an ldap plugin. But understand that I know nothing of ldap protocols, etc. There are two potential approaches to implementing this. One is as an extension to the lib-auth classes and the other is a handler for the federated login implementation. Which is best really depends on what has to be done to implement the ldap protocols.

There are a number of federated login examples both in the supported package and the ZenPhoto20/DevTools20 repository. There is an example implementation of external authority plugin that I can make available. It implemented a single login between zenphoto and MyBB. This approach uses filters to attach to the normal libAuth handling. Note: the MyBB implementation is old and has possibly got out of date.

The other approach to extend the lib-auth would have you create your extension class and override whatever methods of Zenphoto_Authority (and maybe Zenphoto_Administrator) you find necessary.

Your first step would be to look at the external authority implementations and see if you can fit ldap to those. That would likely be the best approach.

At any case, open a ticket on ZenPhoto20 and we can further discuss this.

**Comment by sbillard** [comment]
LDAP is now part of ZenPhoto20
